/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    DropDown: typeof import('./components/DropDown.vue')['default']
    DropDownItems: typeof import('./components/DropDownItems.vue')['default']
    Item: typeof import('./components/Item.vue')['default']
    RangeSlider: typeof import('./components/RangeSlider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
  }
}
